In [8]:
import sys
import os

# Add the directory containing the utility module to the system path
sys.path.append(os.path.abspath('/workspaces/flask_server'))

import pandas as pd
import numpy as np
from utility.lags import sig_lag
from  forecast.forecast_multi import *

In [9]:
df = pd.read_csv('/workspaces/flask_server/test/data/thames_water.csv', index_col=0, parse_dates=True)
df

,chenies_rain,crossness_rain,edenvale_rain,haveringbower_rain,hollandpark_rain,leatherhead_rain,northmymms_rain,num_active_events,num_unique_locs,num_start_events,median_spill_duration,mean_spill_duration,sum_spill_duration
start_day,,,,,,,,,,,,,
12/12/2022,0.0,4.4,1.14,1.38,1.4,0.0,1.6,2,2,2,44.5,44.500000,89
13/12/2022,0.2,2.0,0.28,0.00,0.6,1.2,0.2,1,1,1,540.0,540.000000,540
14/12/2022,0.0,0.0,4.86,0.00,0.0,0.0,0.2,0,0,0,0.0,0.000000,0
15/12/2022,0.2,0.0,1.18,0.69,0.2,0.0,1.6,0,0,0,0.0,0.000000,0
16/12/2022,1.2,0.2,0.02,0.02,0.0,0.0,1.0,0,0,0,0.0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
08/12/2023,14.0,7.0,13.04,0.00,7.4,2.0,8.8,104,36,104,90.0,173.201923,18013
09/12/2023,3.2,2.6,2.42,0.00,3.4,9.7,2.8,300,180,300,195.0,368.263333,110479
10/12/2023,5.4,1.0,4.53,0.00,1.8,1.7,3.2,195,69,195,105.0,217.917949,42494
11/12/2023,10.0,9.6,12.26,8.45,9.2,2.5,4.6,140,46,140,60.0,155.007143,21701
12/12/2023,0.0,0.0,0.01,0.01,0.0,5.2,0.0,393,187,393,135.0,319.804071,125683

In [10]:
lag_list = sig_lag(df = df, max_lag = 30, ts_type="multivariate")
print(lag_list)
print(type(lag_list))

[12, 16, 15, 16, 24, 22, 14, 17, 16, 17, 24, 24, 24]
<class 'list'>

In [13]:
# pred = forecast_multi(df_arg = df, lag_list = lag_list, steps_value = 14, freq = 'D', forecast_method='without_refit')

In [11]:
# print(pred)

In [12]:
metric, predictions = evaluate_model_multi(df_arg = df, lag_list = lag_list, steps_value = 14, freq = 'D', forecast_method='without_refit')

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 6/6 [00:00<00:00, 17.12it/s]

In [14]:
print(metric)
print(predictions)

               levels  mean_absolute_error
0  sum_spill_duration         21928.433259
                  target
2023-10-01   7750.936994
2023-10-02   9415.451164
2023-10-03   9134.174386
2023-10-04   9172.053426
2023-10-05  13217.120989
...                  ...
2023-12-08  10795.125885
2023-12-09  10460.512947
2023-12-10  29329.755242
2023-12-11  23769.195218
2023-12-12  19888.968591

[73 rows x 1 columns]